### ISSUE TITLE
Doesnt let me choose the zip files of rootfs no files even showing up only folders on start Up app

### ISSUE THREAD

**Issue by Mhamhmouth** [KreitinnSoftware/MiceWine-Application#10]
Android 14
Snapdragon 7s Gen 2
12 GB ram

Please make the built in graphics driver of micewine Work perfectly It IS the BEST festure of micewine which makes It different to other Windows emus which all only allow tu use turnip or virgl ( turnip is real good but with some processors like mine Adreno 710 theres no support just dont run evenly ) so how you do it this IS the right way the BEST emus use the android built in driver i dont know how this IS posible but please continúe and make It work

Thankd very mucho for endless hours of free non profit work for everyone , allmighty one help you and all plese

**Comment by KreitinnSoftware** [comment]
Now Zip RootFS Files is not supported, Is a .rat, Download from MiceWine-RootFS-Generator Repository, About Turnip I need to do better tests and some debug, VirGL is not Supported Anymore but I will work on Zink for Mali GPUs later
