### ISSUE TITLE
cant install vc redist

### ISSUE THREAD

**Issue by RZMOVEMENT** [KreitinnSoftware/MiceWine-Application#12]
Hey very nice to see new emulators for android,vc redist aren't installing,whats the reason?

**Comment by KreitinnSoftware** [comment]
Box64 Android Bugs

**Comment by KreitinnSoftware** [comment]
Can you try on Latest Commit?

**Comment by RZMOVEMENT** [comment]
Working now thanks.

**Comment by Crauzer58** [comment]
> Working now thanks.

Close your issue when solved
