### ISSUE TITLE
Cannot Access drive, When Esync on

### ISSUE THREAD

**Issue by Crauzer58** [KreitinnSoftware/MiceWine-Application#14]
I trying to open Drive D and C, but nothing showing and i get this error when open winecfg

'Dynarec will try to emulate a strong memory model with limited performance loss
Dynarec will try to use weaker memory barriers to reduce the performance loss introduce by strong memory emulation
Dynarec will play moderatly safe with x64 flags
Dynarec will optimize CALL/RET
Will expose AVX capabilities
Will expose AVX2 capabilities
Show Segfault signal even if a signal handler is present
Will use 32bits address in priority for external MMAP (when 32bits process are detected)
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT AFP PageSize:4096 Running on ARM64 CPU with 8 Cores
Will use Hardware counter measured at 19.2 MHz emulating 2.4 GHz
Params database has 95 entries
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
BOX64: Didn't detect 48bits of address space, considering it's 39bits
WINE prereserve of 0x10000:0x8000 done
WINE prereserve of 0x110000:0x30000000 done
WINE prereserve of 0x7f000000:0x3000000 done
Warning, older then 2.34 pthread_kill not found, using current one
Counted 48 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/product/bin/:/apex/com.android.runtime/bin/:/apex/com.android.art/bin/:/system_ext/bin/:/system/bin/:/system/xbin/:/odm/bin/:/vendor/bin/:/vendor/xbin/:/data/data/com.micewine.emu/files/usr/bin/:/data/data/com.micewine.emu/files/wine/bin/
Looking for wine
Apply RC params for wine
Applying BOX64_MAXCPU=64
argv[1]="explorer"
argv[2]="/desktop=shell,1280x720"
argv[3]="TFM"
Rename process to "wine"
Using native(wrapped) libdl.so
Using native(wrapped) libc.so
Using native(wrapped) libpthread.so
Using native(wrapped) libm.so
Using native(wrapped) libbsd.so
Using emulated /data/data/com.micewine.emu/files/wine/bin/../lib/wine/x86_64-unix/ntdll.so
Dynarec will try to emulate a strong memory model with limited performance loss
Dynarec will try to use weaker memory barriers to reduce the performance loss introduce by strong memory emulation
Dynarec will play moderatly safe with x64 flags
Dynarec will optimize CALL/RET
Will expose AVX capabilities
Will expose AVX2 capabilities
Show Segfault signal even if a signal handler is present
Will use 32bits address in priority for external MMAP (when 32bits process are detected)
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT AFP PageSize:4096 Running on ARM64 CPU with 8 Cores
Will use Hardware counter measured at 19.2 MHz emulating 2.4 GHz
Params database has 95 entries
BOX64: Wine preloader detected, loading "/data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wine" directly
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
BOX64: Didn't detect 48bits of address space, considering it's 39bits
WINE prereserve of 0x10000:0x8000 done
WINE prereserve of 0x110000:0x30000000 done
WINE prereserve of 0x7f000000:0x3000000 done
Warning, older then 2.34 pthread_kill not found, using current one
Counted 50 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/product/bin/:/apex/com.android.runtime/bin/:/apex/com.android.art/bin/:/system_ext/bin/:/system/bin/:/system/xbin/:/odm/bin/:/vendor/bin/:/vendor/xbin/:/data/data/com.micewine.emu/files/usr/bin/:/data/data/com.micewine.emu/files/wine/bin/
Looking for /data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wine
Apply RC params for wine
Applying BOX64_MAXCPU=64
argv[1]="explorer"
argv[2]="/desktop=shell,1280x720"
argv[3]="TFM"
Rename process to "wine"
Using native(wrapped) libdl.so
Using native(wrapped) libc.so
Using native(wrapped) libpthread.so
Using native(wrapped) libm.so
Using native(wrapped) libbsd.so
Using emulated /data/data/com.micewine.emu/files/wine/bin/../lib/wine/x86_64-unix/ntdll.so
posix_spawn(0x7341ffe0f8, "/data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wineserver", 0x0, 0x0, 0x7341ffe100["/data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wineserver", "", ...], 0x7341ffe488), IsX64=1, IsX86=0 IsScript=0 envp is context->envv
 => posix_spawn(0x7341ffe0f8, "/data/data/com.micewine.emu/files/usr/bin/box64", 0x0, 0x0, 0x7ff14409a0 ["/data/data/com.micewine.emu/files/usr/bin/box64", "/data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wineserver", ""...:1], 0x7ff1441090)
posix_spawn returned 0
Dynarec will try to emulate a strong memory model with limited performance loss
Dynarec will try to use weaker memory barriers to reduce the performance loss introduce by strong memory emulation
Dynarec will play moderatly safe with x64 flags
Dynarec will optimize CALL/RET
Will expose AVX capabilities
Will expose AVX2 capabilities
Show Segfault signal even if a signal handler is present
Will use 32bits address in priority for external MMAP (when 32bits process are detected)
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT AFP PageSize:4096 Running on ARM64 CPU with 8 Cores
Will use Hardware counter measured at 19.2 MHz emulating 2.4 GHz
Params database has 95 entries
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Warning, older then 2.34 pthread_kill not found, using current one
Counted 50 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/product/bin/:/apex/com.android.runtime/bin/:/apex/com.android.art/bin/:/system_ext/bin/:/system/bin/:/system/xbin/:/odm/bin/:/vendor/bin/:/vendor/xbin/:/data/data/com.micewine.emu/files/usr/bin/:/data/data/com.micewine.emu/files/wine/bin/
Looking for /data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so
Using native(wrapped) libc.so
Using native(wrapped) libpthread.so
Using native(wrapped) libm.so
Using native(wrapped) libbsd.so
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
002c:err:wineboot:start_services_process Unexpected termination of services.exe - exit code 0
0040:err:rpc:RpcAssoc_BindConnection receive failed with error 1726
0040:err:service:service_run_main_thread failed to open service manager error 1726
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/win32u.so
Using native(wrapped) libfreetype.so
Dynarec will try to emulate a strong memory model with limited performance loss
Dynarec will try to use weaker memory barriers to reduce the performance loss introduce by strong memory emulation
Dynarec will play moderatly safe with x64 flags
Dynarec will optimize CALL/RET
Will expose AVX capabilities
Will expose AVX2 capabilities
Show Segfault signal even if a signal handler is present
Will use 32bits address in priority for external MMAP (when 32bits process are detected)
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT AFP PageSize:4096 Running on ARM64 CPU with 8 Cores
Will use Hardware counter measured at 19.2 MHz emulating 2.4 GHz
Params database has 95 entries
BOX64: Wine preloader detected, loading "/data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wine" directly
BOX64: Wine64 detected, WINEPRELOADRESERVE="140000000-14007d000"
BOX64: Didn't detect 48bits of address space, considering it's 39bits
WINE prereserve of 0x10000:0x8000 done
WINE prereserve of 0x110000:0x30000000 done
WINE prereserve of 0x7f000000:0x3000000 done
WINE prereserve of 0x140000000:0x14007d000 done
BOX64: Detected running wine with "explorer.exe"
Warning, older then 2.34 pthread_kill not found, using current one
Counted 52 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/product/bin/:/apex/com.android.runtime/bin/:/apex/com.android.art/bin/:/system_ext/bin/:/system/bin/:/system/xbin/:/odm/bin/:/vendor/bin/:/vendor/xbin/:/data/data/com.micewine.emu/files/usr/bin/:/data/data/com.micewine.emu/files/wine/bin/
Looking for /data/data/com.micewine.emu/files/wine/lib/wine/../../bin/wine
Apply RC params for wine
Applying BOX64_MAXCPU=64
argv[1]="C:\windows\system32\explorer.exe"
argv[2]="/desktop=shell,1280x720"
argv[3]="TFM"
Rename process to "wine"
Using native(wrapped) libdl.so
Using native(wrapped) libc.so
Using native(wrapped) libpthread.so
Using native(wrapped) libm.so
Using native(wrapped) libbsd.so
Using emulated /data/data/com.micewine.emu/files/wine/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/win32u.so
Using native(wrapped) libfreetype.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/winex11.so
Using native(wrapped) libXext.so
Using native(wrapped) libX11.so
Using native(wrapped) libxcb.so
Using native(wrapped) libXau.so
Using native(wrapped) libXdmcp.so
Using native(wrapped) libXinerama.so
Using native(wrapped) libXrender.so
Using native(wrapped) libX11.so.6
Using native(wrapped) libXrandr.so
Using native(wrapped) libXcomposite.so
Using native(wrapped) libXi.so
Using native(wrapped) libXcursor.so
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXrender.so.1
0048:err:system:NtUserChangeDisplaySettings Changing L"\\\\.\\DISPLAY1" display settings returned -2.
0048:err:explorer:initialize_display_settings Failed to initialize registry display settings for L"\\\\.\\DISPLAY1".
0048:err:ole:start_rpcss Failed to open service manager
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/ws2_32.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/winspool.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/bcrypt.so
Using native(wrapped) libgnutls.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/ws2_32.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/winspool.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/bcrypt.so
0048:fixme:shell:ISF_ControlPanel_fnGetDisplayNameOf retrieve display name from control panel app
0048:fixme:shell:ISF_ControlPanel_fnGetDisplayNameOf retrieve display name from control panel app
0048:fixme:shell:ISF_ControlPanel_fnGetDisplayNameOf retrieve display name from control panel app
0048:fixme:exec:SHELL_execute flags ignored: 0x00000004
0048:fixme:exec:SHELL_execute flags ignored: 0x00004000
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/ws2_32.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/winspool.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/bcrypt.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/ws2_32.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/winspool.so
Using emulated /data/data/com.micewine.emu/files/wine/lib/wine/x86_64-unix/bcrypt.so
0048:fixme:shell:ISF_ControlPanel_fnGetDisplayNameOf retrieve display name from control panel app
0048:fixme:shell:ISF_ControlPanel_fnGetDisplayNameOf retrieve display name from control panel app
0048:fixme:shell:ISF_ControlPanel_fnGetDisplayNameOf retrieve display name from control panel app
0048:fixme:exec:SHELL_execute flags ignored: 0x00000004
0048:fixme:exec:SHELL_execute flags ignored: 0x00004000
006c:err:winecfg:open_mountmgr failed to open mount manager err 2'

![Screenshot_2024-12-05-12-13-16-489_com micewine emu](https://github.com/user-attachments/assets/e39f5481-a38a-4d08-adf7-57e9e60c8d30)

My phone : POCO F6
Android : 14
GPU : Adreno 735
Micewine latest, RootFS latest

**Comment by KreitinnSoftware** [comment]
This is a box64 android bug, Try to start games using micewine file manager

**Comment by KreitinnSoftware** [comment]
I tried some games with esync and most don't work, Well just use with esync disabled for now
