### ISSUE TITLE
Add dxvk 1.7.3

### ISSUE THREAD

**Issue by teldom14** [KreitinnSoftware/MiceWine-Application#15]
Bro, I think you should add dxvk 1.7.3. There are no graphical artifacts in games on it.

**Comment by teldom14** [comment]
I tested on 8elite propieretary driver

**Comment by teldom14** [comment]
and please add RAM limits for dxvk

**Comment by KreitinnSoftware** [comment]
> Bro, I think you should add dxvk 1.7.3. There are no graphical artifacts in games on it.

I will add tomorrow
