### ISSUE TITLE
Wine doesn't start

### ISSUE THREAD

**Issue by MrPhryaNikFrosty** [KreitinnSoftware/MiceWine-Application#17]
After installing the rootfs of mice wine, the wine couldn't started and it always said 'the wine process is closed'

My device:
Huawei Nova 7
8 GB RAM + 256 GB ROM
Kirin 985

https://github.com/user-attachments/assets/d86765d1-5f8b-401a-b47a-b7f136a6f772

**Comment by KreitinnSoftware** [comment]
You have installed MiceWine-RootFS-aarch64.rat right?

**Comment by MrPhryaNikFrosty** [comment]
> You have installed MiceWine-RootFS-aarch64.rat right?

Yeah, already installed but idk why wine doesn't want to start

**Comment by Insertanamee** [comment]
Same problem here with my hauwei device, here is the log:

Look for renameat2 in loaded elfs Warning, function renameat2 not found in lib libc.so
Look for renameat2 in loaded elfs
Warning, function renameat2 not found in lib libc.so
Error: Symbol renameat2 not found, cannot apply R_X86_64_JUMP_SLOT @0x3f000b6c68 Oxb4246) in /data/data/com.micewine.emu/
Files/wine/bin/../lib/wine/x86_64-unix/ntdll.so wine: could not load ntdll.so: Cannot dlopen("/data/data/com.micewine.emu/files/ vine/bin/../lib/wine/x86_64-unix/ntdll.so"/
x7c490
Error: relocating Plt symbols in elf ntdll.so Error initializing needed lib /data/data/ com.micewine.emu/files/wine/bin/../lib/wine/
86_64-unix/ntdll.so

**Comment by KreitinnSoftware** [comment]
Missing libc functions, WTF

**Comment by KreitinnSoftware** [comment]
what your android version?

**Comment by Insertanamee** [comment]
Emui 12, so android 10. No longer receiving updates.

**Comment by KreitinnSoftware** [comment]
You can try now, I recompiled rootfs with Android 10 support

**Comment by Insertanamee** [comment]
It works now, thank you.
