### ISSUE TITLE
Press back Button to see log, sometime not working and kill wine process

### ISSUE THREAD

**Issue by Crauzer58** [KreitinnSoftware/MiceWine-Application#19]
So There is a big bug when Esync on, we cannot Access drive, so u suggesting to open with micewine file manager #14. But when i open with Filemanager my game crash, and i cant see the log, because when i press back button, the wine process is stopped.

**Comment by KreitinnSoftware** [comment]
Please try in latest commit, I made some changes and this problem probably fixed
