### ISSUE TITLE
Storage not working

### ISSUE THREAD

**Issue by ODog235** [KreitinnSoftware/MiceWine-Application#21]
Internal storage isn't recognized in the desktop environment, (winlator's file manager) and running executable directly from the app without the desktop environment causes wine to never start. S24 base model 128GB (the winlator app itself works fine).

**Comment by Insertanamee** [comment]
Have you tried updating prefixes in the start menu? Or enabling/disabling wine esync?

**Comment by ODog235** [comment]
I've tried turning off and on e-sync; as for prefixes, I'm not really sure how to do that.

**Comment by ODog235** [comment]
Oh wait nvm I found it

**Comment by ODog235** [comment]
Oh ok, yeah updating the prefixes, then restarting fixed it. Thank you!

**Comment by ODog235** [comment]
Well no games are starting anyways

**Comment by Insertanamee** [comment]
> Also is there no way to run regular linux apps (instead of windows) on this?

Dont think so. They'd need to be compiled for bionic I'm pretty sure.

**Comment by Insertanamee** [comment]
> Well no games are starting anyways

Yeah still very buggy. Needs better box64 and dxvk support.

**Comment by Insertanamee** [comment]
Also consider closing this issue.
