### ISSUE TITLE
BOX64: Didn't detect 48bits of address space, considering it's 39bits

### ISSUE THREAD

**Issue by JohnGodgames** [KreitinnSoftware/MiceWine-Application#25]
Could this be a serious error or just a false alarm?MiceWine uses 9.0.

https://github.com/ptitSeb/box64/issues/1365
Closed as states it's a wine problem

https://github.com/Pi-Apps-Coders/files/commit/d4e9180610689f09e65a8fa88121a339bce1745a
Resolved in Wine 9.13

**Comment by KreitinnSoftware** [comment]
This is a harmless box64 warning about the kernel
